### ISSUE TITLE
enable Github code scanning

### ISSUE THREAD

**Issue by grrrrr** [anish-sahoo/ExpiryDateReminder#4]
I note that in the PrivacyPolicy.md you mention notifying about security issues.  To help stay on top of this your self, I'd like to suggest enabling  Github's Code scanning tool.

This tool is free for Public and OpenSource projects and from what I can see, ExpiryDateReminder meets requirements.

[Blog post about Security code scanning](https://github.blog/2020-09-30-code-scanning-is-now-available/)

[Steps to take to enable code scanning](https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/enabling-code-scanning-for-a-repository)

**Comment by anish-sahoo** [comment]
Hi! I just added CodeQL scanning to this repository, and its running as I write this comment!
